import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import { Toaster } from "@/components/ui/sonner"
import Navbar from '../components/layout/Navbar'; // Ajusta la ruta si es necesario
import Footer from '../components/layout/Footer'; // Asumiendo que tienes el Footer

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 bg-[url('@/public/images/Hotelsa.webp')] bg-cover bg-center bg-fixed flex flex-col min-h-screen`}
      >
        <Navbar />
        <main className="flex-grow">{children}</main>
        <Footer />
        <Toaster richColors />
      </body>
    </html>
  );
}
